dist: bionic
addons:
  apt:
    sources:
    - sourceline: deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/
        /
      key_url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_18.04/Release.key
    packages:
    - buildah
language: go
go:
- 1.17.x
cache:
  directories:
  - "${GOPATH}/pkg/mod"
  - "${GOPATH}/pkg/sumdb"
env:
  global:
  - GO111MODULE: 'on'
  - RELAY_EMAIL: team-relay-ops@puppet.com
  - secure: Z+Ogj4+YIQWOjLFvyXLnaoqE9iYNosru6t0+TiyIz23wDKLJt8cd4uKsIpYjiM+S8IvjOHTqsufzverjqQxuTDzexrX1kaESFK5B+y0BucH2YvWBhuglz+95+GRfkVWSNBH++V1GO81S3cPPr8xm1yA7npQlnZK349Xn6OeBjJhDlle7mvbycdHslI2MrTQrhKzb6mOclQ8P9qbzu7/U254+uHz9x3MyQuDgLKL4e255aq3KJeOapNNSgWLFr4W3wS7IQKUqp6C/RqiVf6ZoskNRAIeHH7MlvH+YLPsVgBDNYCltZbQF/ADNEyBoiqZc+aFYP3jaAbtvIAxWDb2IBpeJejPhKxlgkug5tdo0GWiJYYCNk8Q8Xhhx5WqSOWYnbfPQPIcQNBRuc4Xw/nV0w3+lBoXfItZcNnGEhYHC55kvxLkWRLpSECulQ1y+05OMIP3X1kj3B36eT0Al4kT9KsLS82FPtvjQgqemZMm/Io5BVqg/poYh7l1B3S8E0IxLw73UZEP4M4a1WRINxmIqXjLObYq8osIN8as9+m199cxOHTs3dhbNaj1BtcJHEsqXEQsN2lI8q12Zcw3A9eg4ZjlMG2/SPRVxzJ+WYhr1/Nd4bh7NZGDizh66ivil3DVDN8WCFCwxjg8cwd+SiUUo9xCgRoLTED7/BAsyPv6/BUY=
  - DOCKER_CONFIG: "/tmp/.docker"
  - DOCKERHUB_USERNAME: relayshro
  - secure: EGWWMhmIJjCPOh1ADo817H6170v36T8XfFQoUiuOgba7971UGFLIWZeun+ZGZI75inVPBMNDYuVktjp46VsWyyMGq4c+t29YaS6o5gwyT1eAGkKjsmVKVR3xJLr6XQuCaFN2SZkS/nuVfov/PBIkO7H2tq8ffrZOCVrEO1YmtlTUOuoe5CGEdi+ipzbDEspSmEcoGxXp1Nfti1PVH2T725oZxo1qzjK4fAKf847C3p+jF548E9c1Pyfcm7wZiaakPhBUIIHzgYFXOkhGpurHiVVUSMvWGFrSsBVhrIT3tWpSVOqwTMq4DVJRBiJkydCNX7ezCAjMmKoqu/aBv5uaDCmdinIsgWAAB8QLwM3slDNyQ85F9UdEMfXxcPwMI0NOJKyL1iQ1wnfPm7DeBInvBsLP6RwFkePjbvJWnFbmmp7szgcW5vqLNH1xlb6Te7bsqiFsYD75VOIT283FRQSd7Luade5bV/mVgXt4h87BYeZe+eslGmS8NB/tS1CFj3vX6lPsH4hWJNizz5czTgCPik2HfsvTuxzClSuN+hSrUsYPGWWnx3JHU9VfiOK6XKstRvBIir6V++n1SWolzk4XXVyTXViDcSk21pwJOXv6hz1HJjO/vVFJY0qzJm5tn5GThc9yEbp2IaIPqvz8kt/4mJFIQEupvZrbJrgSE4N56/M=
  - secure: nhP/GZuRblUOOofcA5qiJjEABdtzjIHPFJ2+qVbWpDFp+F7p9QxErePSm2/uCRsN19He3QQBdvtnHghbrzXWe7apGvxwOWs+FLzD1m8/uB2rd8R7Mx9YMgSGEtdSknX5xCCTTH7Mpv8XL7DTdg0pw3d2loN31QOin6jKOxvzeuRW02QZWnQeevw9gcg7whMrGCDR+BVk8LYhvCstTNeeLqP1G3q4T+YLNhQhjaDEklJI0YGSMxsekXVFZSMN6HN0w/5pdksu0ITs521Lo8W2BJHDZfzniWYVOAsgUdN+sxgHLyL+xWqtrfI3evrXpy3iU6I+r2dQE5cyYKVNWogGv3Qfb1AqVwLDOANr6wTO6myzelgliKZ3+Eji4lSQoiXrMdV7tNpZ1kvGlNS5dUpFj4xOQB2r5s0r1J7VBA7QT0XNDaPso2rJ6UigmHhbywE0j1/ptnO1MKQ2oShKX9wLBZkL1V1m9DHtheTW+jAc1hkaDzVx1uIA3eFCgS010GORxjZegqOcHXEJskh4Kmbh5OXcVwJL13GAN97x0HKgj5otVvxHsUCGIqCylpwYjS0mYscjkg+vpuT0mAbo34amxbKwcV6LEjQaMFVxRxw+J0AwM41PeFfO7/WNLBxz6Gb66VFk10GWiA3oCydnlF/KdAACHkCYL7rv8Pk7A5j/i/k=
install:
- mkdir -p "${DOCKER_CONFIG}"
- echo '{}' >"${DOCKER_CONFIG}/config.json"
- docker login --username "${DOCKERHUB_USERNAME}" --password-stdin <<<"${DOCKERHUB_PASSWORD}"
stages:
- check
- test
- build
- deploy
jobs:
  include:
  - stage: check
    before_script:
    - go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.33.0
    script:
    - golangci-lint run
  - stage: test
    before_script:
    - go get gotest.tools/gotestsum
    - openssl aes-256-cbc -K $encrypted_c51f15aa433d_key -iv $encrypted_c51f15aa433d_iv
      -in scripts/nebula-ci-service-account.json.enc -out scripts/nebula-ci-service-account.json
      -d
    script:
    - GOOGLE_APPLICATION_CREDENTIALS=$(realpath scripts/nebula-ci-service-account.json)
      ./scripts/ci test
  - stage: build
    before_script:
    - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk;
      export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com |
      bash; fi
    - source "$HOME"/google-cloud-sdk/path.bash.inc
    - openssl aes-256-cbc -K $encrypted_bdcc93d4c365_key -iv $encrypted_bdcc93d4c365_iv
      -in scripts/nebula-gcloud-service-account.json.enc -out scripts/nebula-gcloud-service-account.json
      -d
    - gcloud auth activate-service-account --key-file scripts/nebula-gcloud-service-account.json
    - gcloud --quiet auth configure-docker
    script:
    - "./scripts/ci build"
    - "./scripts/ci release"
  - stage: deploy
    script:
    - "./scripts/ci deploy"
